cmdargs:
  # Checking more strictly
  # severity: style_problem

  # Enable coloring
  color: true

  # Enable Neovim syntax
  env:
    neovim: true

policies:
  # Disable a violation
  ProhibitImplicitScopeVariable:
   enabled: false

  # Enable a violation
  #ProhibitSomethingBad:
  #  enabled: true
